### ISSUE TITLE
Improve scheduling interface messaging wrt online training availability

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#1122]
The end-user scheduling interface (page Me > Schedule / Sign Up) will inform the end user when one or more requirements have not been meant. A common one is not completing online training.  In the case where Online Training (OT) has not been opened up yet, the user will receive the same message regardless if OT was open and they not completed  the OT course.

"The online course has not been completed"

The setting OnlineTrainingEnabled can used to provide a better message for when OT has been disabled.

**Comment by flwyd** [comment]
@srabraham is interested in this one.

**Comment by srabraham** [comment]
Looks like @mikeburg [already took care of this](https://github.com/burningmantech/ranger-clubhouse-api/pull/1041/files#diff-c028e33253dd42b45acfe51bf9afa2867c13f37f9f10a871c086abce574c7c40R95) on Feb 4.
However, he [changed the logic again on June 15](https://github.com/burningmantech/ranger-clubhouse-api/pull/1171/files#diff-c028e33253dd42b45acfe51bf9afa2867c13f37f9f10a871c086abce574c7c40R97-R98), and that code (which is still current) looks kind of suspicious. Was that just a temporary tweak for after online training ended?

**Comment by mikeburg** [comment]
This issue is stale.  The scheduling Online Course blocker went through several iterations with T.A. and Council involved from went the original issue was opened to the most recent patch listed.

Closing out.
