### ISSUE TITLE
Add Vintage Designation to Bulk Lookup Output

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#1140]
To Support Annual Ranger Status updates, it would be handy to be able to lookup vintage designation without SQL.

**Comment by rangerthreepio** [comment]
Request also add "Total Years" to this table.

**Comment by srabraham** [comment]
@rangerthreepio: Currently the [bulk lookup page](https://ranger-clubhouse.burningman.org/client/admin/bulk-lookup) has columns
Callsign, Status, Name, Email, Last worked

and the CSV export on that page has columns
Callsign, First Name, Last Name, Status, Email, Last Worked

Is it correct that you're asking for additional columns on both of the above for "Vintage" (true/false) and "Total Years" (int)?

**Comment by rangerthreepio** [comment]
Affirm that is the request. Also, this annual process is due to start "soon." Please do let me know when the fix is in place and I will happily test it!

**Comment by srabraham** [comment]
These two PRs ought to resolve this. I validated them locally with Rangers of various tenures. @mikeburg @flwyd 
https://github.com/burningmantech/ranger-clubhouse-api/pull/1281
https://github.com/burningmantech/ranger-clubhouse-web/pull/1465

**Comment by srabraham** [comment]
Fixed. The code is in staging now and should hit prod soon-ish
