### ISSUE TITLE
SO WAPs should inherit dates

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#1163]
SO WAPs do not inherit the date of unclaimed items, thus when Rangers request SO WAPs, but no RPT or SC, the SO WAPs are undated by default and there is no code which prevents that from remaining in the database until someone notices and fixes it. This happened in 2019.

_Originally posted by @rangerthreepio in https://github.com/burningmantech/ranger-clubhouse-web/issues/173#issuecomment-534800393_

**Comment by mikeburg** [comment]
Appears to be working. Closing out.
