### ISSUE TITLE
Please add LE, LEO, DEAD, DEATH to the correct sections of the reserved handle lists

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#1234]
By decision of Council 4/26/2022. 

thank you!

**Comment by rangerthreepio** [comment]
And by these we mean in addition to "L E"  and "L E O"

**Comment by flwyd** [comment]
Resolved via https://github.com/burningmantech/ranger-clubhouse-api/pull/1274
