### ISSUE TITLE
Inactivate positions should not appear on Shift Lead Report

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#1238]
The Intercept Operator position is being inactivated. When inactivated on staging, IntOpr still appears as a property of a person in the Shift Lead report. Inactive positions should not be displayed here.

![intopr](https://user-images.githubusercontent.com/27961730/166158408-0e161cfe-f5cf-4f90-96da-875f968c3c3d.png)

**Comment by flwyd** [comment]
I think I removed it from the list earlier this year, though it looks like I didn't remove it from the legend at the bottom of the page.

**Comment by mikeburg** [comment]
I meant to close this out a while ago -- it's been fixed.
