### ISSUE TITLE
Add Operator - Smooth to the Coverage Report

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#1239]
The new Operator - Smooth position (position_id = 142) should be added to the Coverage Report. This would involve anyone signed up as Operator - Smooth appearing in the Opr column of the report, optionally but ideally with (Smooth) noted along with the person's callsign - similar to how (Mentee) and (Partner) appear on the report below.

![image](https://user-images.githubusercontent.com/27961730/166158930-5e181866-ca4f-4b79-81da-0e3b5d2072d9.png)

**Comment by mikeburg** [comment]
Added, please test!

**Comment by mikeburg** [comment]
Appears to be working. Closing out.
