### ISSUE TITLE
Update the 'Teams' list in the Trainer's Report

### ISSUE THREAD

**Issue by Nobooty** [burningmantech/ranger-clubhouse-web#1255]
The trainers-report Teams column list needs updating to remove some "all Rangers" positions from TITLE_MAP.

Specifically Remove:

- ECHELON_FIELD,    // All Rangers
- GREEN_DOT_MENTEE,  // Not technically on the GD team yet
- HQ_TRAINING,  // All Rangers
- SANDMAN // All Rangers

Might want to add:
[Position.ECHELON_FIELD_LEAD] :  'Ech',
[Position.RSC_WESL]: 'WESL'

Could also add [Position.GREEN_DOT_LEAD]: 'GD', to replace the missing _SHORT, but as they should always have Dirt_Green_Dot it's kinda redundant.

**Comment by mikeburg** [comment]
Is this a Green Dot request or a Training Academy request?

**Comment by Nobooty** [comment]
HQ ART Trainer request since we can't tell who's experienced if everyone is marked HQ.
And GD ART Trainer request, for the same reason.
And apparently I need to update my notifications filter.

**Comment by flwyd** [comment]
Abraham is interested in taking this one.

**Comment by srabraham** [comment]
That's me
