### ISSUE TITLE
Add VIPs to "in use" category for Handle checker

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#1264]
Presently, in the callsign checker, with "Retired Ranger" box unchecked searching for "Muppet" returns "2 rhyming syllables with Muppet" 

When "Retired Ranger" is checked, searching for "Muppet" returns "Muppet is already in use." 

Muppet is both a Retired Ranger and a VIP. VIP matching callsigns should appear as "In Use" ALL THE TIME just like Retired Rangers do when the retired rangers box is checked.

**Comment by rangerthreepio** [comment]
@mikeburg @flwyd this item is desired for VC work starting April 1, 2023.

**Comment by mikeburg** [comment]
@flwyd Are you around for this?

**Comment by mikeburg** [comment]
VIP category (aka TWII person) has been implemented, the retired checkbox is checked by default. Closing out.
