### ISSUE TITLE
Better sorting for person autocomplete

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#127]
I typed [star] into the person search box and got the following autocomplete results:

*   Scooter (deceased) — "star" soundex, no exact field match
*   Amadeus (active) — "star" in email
*   Bliss (active) — "star" in last name
*   DarkStar (inactive) — "star" in handle
*   Good Start (inactive) — "star" in handle
*   Green Bastard (active) — "star" in handle
*   HandPrint (inactive) — "star" in last name and email

I suspect that callsign lookup is more common than other field lookup.  It's certainly more common at the HQ Window when lookup needs to be fast.  So I'd recommend sorting handle matches before other field matches.

I'd also recommend sorting results by status: it's probably more likely that someone will select an active or prospective ranger than a deceased or retired one.

If we want to get fancy, matches at word boundaries (including infix capitals) should sort before other substring matches.  E.g. DarkStar and Good Start would sort before Bastard.

**Comment by mikeburg** [comment]
A bug crept into the callsign search resulting in the random ordering as seen above. The search order has been corrected to  be exact matches, begins with partial matches, partial match in any position, followed by default world name matches.

It should be noted that the search modes Person Manager versus HQ Window filters differently. Person Manage is more permissive allowing year-round teams to do more permissive searches. Whereas HQ Window only selects for active, PNVs, or soon-to-be-active-again (i.e. inactive, inactive extension, retired) status callsigns.
