### ISSUE TITLE
Export a .vcal file from the Clubhouse for mobile users

### ISSUE THREAD

**Issue by vought** [burningmantech/ranger-clubhouse-web#1350]
The print feature is awesome for a paper copy of one's schedule. As a user, I'd also like to download a calendar file (.vcal or .ical) comprising my shifts that I can add to my own calendaring application. 

This would allow me to set alarms and schedule my time commitments without finding that printed copy, inputting my schedule manually, and would allow me to set alarms on my mobile device more easily.

**Comment by mikeburg** [comment]
Implemented. Closing out.
