### ISSUE TITLE
Roll call interface recommendation

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#136]
To help expedite check ins for burn perimeters, it would be nice to have a roll call interface. 

When a Burn Perimeter (BP) check in starts, the person managing the BP check ins would go to the roll call page, and pull up a list of callsigns who are signed up for the BP.

Next to each callsign on the page would be at button. Clicking the button would mark the Ranger as checked in.

An example would be Bucket walks in front of HQ on Burn night with a tablet, pulls up the roll call interface, and is shown everyone who is signed up. He announces to the waiting Rangers roll call is about to being, waits a moment for the chatter to die down, and then proceeds to read off the list of names. "Hubcap"  he yells. Hubcap responds, "Hubcap, here". Bucket clicks Hubcap's name, the Clubhouse records Hubcap as being signed in for the Burn, and Bucket go on to the next name in the list. Lather. Rinse. Repeat.

The interface is suited to check in Rangers who do not need gear. Sorry Sandmen.

Credit goes to Mailman for suggesting this.

**Comment by hariboukis** [comment]
Two enthusiastic thumbs up!

—Socrates 



--------------------------------
Hari Boukis
Mobile: 925-351-7772
Mobile e-mail: Hari@Boukis.com
Fax: 925-956-7013
--------------------------------
Sent from mobile phone
--------------------------------


On Jun 3, 2019, at 9:20 AM, mikeburg <notifications@github.com> wrote:

To help expedite check ins for burn perimeters, it would be nice to have a roll call interface.

When a Burn Perimeter (BP) check in starts, the person managing the BP check ins would go to the roll call page, and pull up a list of callsigns who are signed up for the BP.

Next to each callsign on the page would be at button. Clicking the button would mark the Ranger as checked in.

An example would be Bucket walks in front of HQ on Burn night with a tablet, pulls up the roll call interface, and is shown everyone who is signed up. He announces to the waiting Rangers roll call is about to being, waits a moment for the chatter to die down, and then proceeds to read off the list of names. "Hubcap" he yells. Hubcap responds, "Hubcap, here". Bucket clicks Hubcap's name, the Clubhouse records Hubcap as being signed in for the Burn, and Bucket go on to the next name in the list. Lather. Rinse. Repeat.

The interface is suited to check in Rangers who do not need gear. Sorry Sandmen.

Credit goes to Mailman for suggesting this.

**Comment by wsanchez** [comment]
Neat.  I could see it working for dirt shifts… if you have an event radio.

**Comment by mikeburg** [comment]
The interface has been created and could use a review.

**Comment by mikeburg** [comment]
O.N.E. 2 was able to test this extensively. Closing out.
