### ISSUE TITLE
Green Dot highlighting on Shift Lead report only works on even-numbered rows

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#1370]
On the [Shift Lead Report](https://ranger-clubhouse.burningman.org/client/reports/shift-lead?year=2022), people with the Green Dot position (GD abbreviation) are highlighted in green so it's easy for Khaki to see which Green Dots are in the field.  However, the Bootstrap table striping ends up taking precedence on odd-numbered rows (despite the `!important` on the `.bg-shiift-lead-greendot` class), so this visual highlight is only visible on even-numbered rows which would otherwise have a white background.

Observed on Chrome 104 on MacOS.

**Comment by mikeburg** [comment]
Fixed. Closing out.
