### ISSUE TITLE
"On playa only" filter shows retired Rangers with Dirt position

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#1381]
I was curious which Rangers had been marked on site, so I ran the People By Position report.  I expanded the Dirt section, expecting that to be a good source for "everyone on playa", but noticed a bunch of retired rangers in the list.  Looking closer, I realized the list was _all_ retired Rangers.  I think what's happening is the People By Position report only shows people with an "all rangers" position if their status indicates they shouldn't have that position. But when the "on playa only" box is checked, it seems to me that we shouldn't show anyone who's not on site.

We also might want to consider getting rid of the "don't show people in Dirt because everyone's got that position" special case if the on-playa filter is checked, since I haven't found another way to see a list of all the people on playa.  Maybe that should be a separate report, though.

**Comment by mikeburg** [comment]
This was fixed a while ago. Closing out.
