### ISSUE TITLE
Can't set self-bonk status on Alpha Acceptance page

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#1385]
2 Step attempted to set the status of two Alphas to "self-bonk" on the Alpha Acceptance page during mentoring.  The clubhouse showed what looked to be a client-side validation error that the status was invalid.  The alphas were able to be set to either pass or bonk, just not self-bonk.  No other self-bonks were recorded this year, so it's knot known when self-bonks were last successfully working.

Possibly related, 2 Step noticed that self-bonk is not in the Person Status select list on the main person page.  I'm not sure if we previously had `self-bonked` as a separate status from `bonked`.

**Comment by mikeburg** [comment]
Fixed on the Mentor Assignment interface (Alpha Acceptance is an interface to simply print out the acceptance sheets handed out to mentors at the beginning of the Alpha shift). 

Self-Bonk is only a mentor status, and not a person account status. If the person was bonked, or self-bonked, the account will be converted to 'bonked' either way. Unless the mentors fell the person should never reapply, then the account should be set to 'uberbonked'.

After the event, any bonked account will be converted to past prospective.
