### ISSUE TITLE
Positions admin page should designate relevant teams for trainer's report

### ISSUE THREAD

**Issue by srabraham** [burningmantech/ranger-clubhouse-web#1471]
The trainer's report lists teams for each Ranger (see screenshot). Currently we do client-side combining and filtering of positions to get to the values that are actually shown in the UI, via [this TITLE_MAP](https://github.com/burningmantech/ranger-clubhouse-web/blob/ce8dc2a036e0288cbf6adc404fb99be203686786/app/controllers/training/session/trainers-report.js#L6). This means that updates to what gets shown need to be done by members of the tech team, e.g. this request via an Issue https://github.com/burningmantech/ranger-clubhouse-web/issues/1255.

@mikeburg points out that we should instead achieve all this via a new column on the positions table, something like "show on trainer report", which would be fed through the API and lead us to not need that TITLE_MAP. The value of that column would be set from the positions admin page.

![image](https://user-images.githubusercontent.com/23407555/200866964-fc8229d0-63b7-4e45-8b41-ce28514aa1d1.png)

**Comment by srabraham** [comment]
This is Mike's idea, and I'm just relaying it here from a call we had. The one thing I'm not so clear about is what values are actually desirable in that "teams" column in the trainer's report. We could just list the position short titles instead of "teams", though not all positions even have short titles, and this might lead to much longer values in that column. This is just to say that the TITLE_MAP is doing some additional work for us, not just filtering things out, but also grouping positions into simple representations ("GD" for all green dot positions, etc.)

**Comment by mikeburg** [comment]
Thank you @srabraham -- closing this out.
