### ISSUE TITLE
Add HQ Training (Refresher) to the Position Sanity Checker

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#160]
Each year the HQ Training (Refresher) position should be revoked from any account that has not worked one of the following HQ Window positions in the last 3 years.

HQ Lead
HQ Lead - Pre-event
HQ Short
HQ Supervisor
HQ TOD
HQ Trainer
HQ Window
HQ Window - Pre-event
HQ Window - Sandman

In additional, the HQ Trainer (Refresher) position should be granted to any account which did work one of the above positions within the last 3 years.

The grant and revocation of the position is a good candidate for the Position Sanity Checker.

**Comment by mikeburg** [comment]
The sanity check may need to compensate for the 2020 event being cancel.

**Comment by Nobooty** [comment]
FYI: No HQ Refresher Training are planned for 2022. So this can be a 2023 thing.

**Comment by mikeburg** [comment]
HQ Refresher didn't happen in 2022 or 2023. Since it's been almost 5 years, we'll consider this dead. Will revisit if the refresher course becomes a thing again. Closing out.
