### ISSUE TITLE
Multi-ticket holders granted no WAPs if they have SCs

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#165]
Ticketing code automatically selects the oldest credential when displaying what to claim or bank in Tickets and Stuff. Grant WAPs maintenance function explicitly doesn't grant WAPs to people with Staff Credentials. This means a user with an RPT (say, 2017) and an SC (say, 2018), will see their RPT auto-selected by the clubhouse, and no WAP issued, but then sees the "You have no WAP, this is probably a mistake" under WAP. 

Code should either select the oldest SC, or issue WAPs to anyone with 0<RPTs OR SCs<1.

**Comment by mikeburg** [comment]
The code has been changed to grant  a WAP to anyone who has a RPT on file OR anyone who does not have RPT and SC. (has RPT || (not RPT && not SC))

**Comment by rangerthreepio** [comment]
Solved - Grant WAP button now adds waps to folks with an RPT OR no SC. Instead of just without SC.

Need more logic to give end user options about claiming or banking  multiple items.

**Comment by mikeburg** [comment]
Closing out.
