### ISSUE TITLE
Manage Access Docs counts SCs as WAPs

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#166]
Manage Access Docs page counts each SC as a WAP when displaying "weird stuff." This means someone with two SCs has 2 WAPs, which is flagged as weird. It also means someone with an RPT, a WAP, and a banked SC, has 2 WAPs, which is flagged as weird. 

Suggest that the counter does not count SCs as WAPs (they aren't), and then what problem does that cause?

**Comment by mikeburg** [comment]
The behavior has been changed to not count SCs as WAPs in weird stuff. The change should alert about a person who has a SC *and* a WAP.

**Comment by rangerthreepio** [comment]
love it.

**Comment by wsanchez** [comment]
fixed
