### ISSUE TITLE
Export Access Docs displays more items than actually claimed

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#167]
Export Access Documents is displaying access documents for export to TRS that have not been claimed. > In the case of Rangers with multiple "event entry credentials" who claim one of their items but not the other(i.e. claim one SC, bank the other), both SCs show up as claimed in Export Access Docs view, with their corresponding unique RADs. This is a showstopper for this year.

**Comment by rangerthreepio** [comment]
This bug may actually be claiming ALL available RADs for every Ranger who claims anything. 

Ranger Adonis is shown having claimed his RPT ONLY, for mail. Export Access Docs shows that he has claimed his RPT+VP (delivery type "UNKNOWN"), as well as his WAP.

**Comment by mikeburg** [comment]
The selection was wrong on the backend - pretty much everything was pulled in and not selected for just the claimed item.

A fix has been pushed to production.

FYI - the filters are still untouched. Waiting on confirmation from Safety Phil.

**Comment by plapsley** [comment]
@mikeburg Sorry, I'm missing some context -- what info are you waiting on me for?

**Comment by mikeburg** [comment]
@plapsley yes, you are missing some context! emailing you in a bit.

**Comment by rangerthreepio** [comment]
Worth revisiting this. I am filing a new report for another showstopper bug of treachery which is probably directly related...

**Comment by wsanchez** [comment]
@rangerthreepio Please confirm this is fixed

**Comment by rangerthreepio** [comment]
Awaiting a test server that is set up for that magical time of year we call
"ticketing season"

**Comment by techxorcist** [comment]
Tested by Citizen and 3PO.
