### ISSUE TITLE
Death to (NR) / make sure status included in reports

### ISSUE THREAD

**Issue by plapsley** [burningmantech/ranger-clubhouse-web#172]
Right now, non-Rangers usually have (NR) in their callsigns, e.g., LapsleyP15(NR).  This allows people to tell at a glance from the handle whether someone is a Ranger or not.  But it's a hack.

Better would be to:

1. Make sure reports include Ranger status, and/or

2. Are gated by Ranger status (e.g., if you're looking at the auditor or past prospective report, you don't need NR; similarly, if you filter by status in active, inactive, retired, you don't need the NR)

**Comment by corprew** [comment]
It's handy for the RRN to be able to see this in training reports, more regional rangers are starting to show up to audit trainings (& in some cases things like the green dot training.)

**Comment by mikeburg** [comment]
Closing out. The account status is included on reports where it counts.
