### ISSUE TITLE
Distinguish ID name from default world name

### ISSUE THREAD

**Issue by chaoticbear** [burningmantech/ranger-clubhouse-web#1728]
Many users have a primary Default World Name `default_name` which is different from the name on their ID `id_name`. It's not immediately clear to me that the Personal Info name fields require an `id_name`. In my case it became clear when looking at my tickets and stuff and I deduced the name they're going to check for is the one on my ID, even though that is also not explicitly stated in the Tickets & Stuff area.
![image](https://github.com/burningmantech/ranger-clubhouse-web/assets/2730052/9c272dd5-0f1d-4769-9317-1c2224e4b064)

A couple options come to mind:
 1. The simple fix for this would be to state next to the personal info fields that this should match your ID for staff credential, WAP & Vehicle pass distribution. 
 A note here:
![image](https://github.com/burningmantech/ranger-clubhouse-web/assets/2730052/c4520dfc-4d69-4f43-9f11-84a44662c383)
And here:
![image](https://github.com/burningmantech/ranger-clubhouse-web/assets/2730052/e49629b2-d676-4757-94ea-a7b91b995cea)

 2. The more complex option involving a data model change would be to add fields for `default_name` & `id_name`. The benefit would be that for, folks who's `id_name` is a `dead_name`.
   2a. The `id_name` could be hidden behind a show/hide toggle or button opening modal window or other option that requires an extra click to un-obscure the name.
   2b. The `id_name` could be only shown to users with certain permissions assigned to users handling ticketing, or other cases where an ID may need to be verified. 
   2c. A combination of the two above.

**Comment by joshfleming** [comment]
#1045 is Relevant to this issue so you might call this a more specific duplicate.

**Comment by mikeburg** [comment]
The Volunteer Coordinators has discussed a similar issue concerning individuals who may be in the process of changing their legal name. 

The enhancement deployed a couple of weeks ago adds a preferred first name field, and states how the legal & preferred names are used.

Closing this out.,
