### ISSUE TITLE
Editing WAP Dates with BMID Interface or Bulk Uploader is Treacherous

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#173]
It appears that using the Edit BMID interface OR the bulk uploader to edit the WAP Date selects the oldest item, however, if the claimed item changes AFTER the Edit BMID interface has been used, the interface continues to ONLY edit the same item it originally edited. Similarly, if the BMID interface or bulk uploader is used after an item is claimed, it may edit a banked item, rather than the claimed item.

Use case: Prior to ticketing opening, Ticketing Team sets up SITE WAP dates using the bulk upload tool or the BMID interface. The interface sets the WAP date of the oldest items ONLY (WAPs will be the newest because they are granted THIS YEAR, SCs will always be older, RPTs dont have dates). 

Then, ticketing opens, and Hubcap says, I don't want to use my SC, I want to use my RPT. Ticketing Team changes the swaps the claimed/banked. The date won't carry over automatically (that's ok, we'll _probably_ notice), but the BMID interface and bulk uploader will "stick" to the item it already modified (this relates to WAP ID #). So when Chameleon decides to unapprove or change their date(via BMID or bulk uploader), it will affect the now _banked_ item, which isn't obvious in the individual Edit BMID interface and is invisible if done in Manage BMIDs interface or with the bulk uploader.

Similarly: Bucket opens his ticketing, and sees his RPT was selected by default, but he has no WAP (because he has an SC). He asks us for a WAP because he wants to bank his SC. Now imagine we actually catch that he should have a special WAP date because the bulk uploader set his SITE WAP date on his SC. However, any changes to his WAP date from the BMID interface or bulk uploader after we've claimed the RPT and WAP will continue to affect the SC

**Comment by mikeburg** [comment]
The fix is to update all WAP types (SCs & Work Access Passes) with the desired access date. The backend will also use the first WAP doc that has been already claimed or submitted when trying to figure out what the access date is for a BMID.

https://github.com/burningmantech/ranger-clubhouse-api/pull/169

**Comment by rangerthreepio** [comment]
>
> The backend will also use the first WAP doc that has been already claimed
> or submitted when trying to figure out what the access date is for a BMID.


To clarify: does it currently use the WAP doc with the lowest number?
earliest source year?

And you are proposing that it would use the lowest numbered claimed or
submitted doc, and if none are claimed or submitted, just the lowest
numbered qualified doc?

**Comment by mikeburg** [comment]
> To clarify: does it currently use the WAP doc with the lowest number?
earliest source year?
Originally the lowest RAD number was used, and after this change, the lowest source year is now used. RAD numbers are really database id numbers and may not actually reflect the "earliest" ticket.

> And you are proposing that it would use the lowest numbered claimed or
submitted doc, and if none are claimed or submitted, just the lowest
numbered qualified doc?

Exactly. The order of preference in order:
- A claimed or submitted WAP type
- the earliest access date
- the earliest source year
- the lowest ID number (only used if two tickets came from the same source year)

Is this acceptable?

**Comment by rangerthreepio** [comment]
I think that is OK, but I'd feel better with Phil's brain concurring.

And to clarify: would this resolve the "stickiness"?

**Comment by mikeburg** [comment]
> And to clarify: would this resolve the "stickiness"?

It should. When the access date is updated thru the BMID Interface, all SC or WAPs (not SOWAPs) for the person will be changed regardless if the SC or WAP has been claimed.

**Comment by rangerthreepio** [comment]
I think that's ideal. If we have "1 WAP Date" then it really needs to apply
to all items, regardless of what is ordered for them and when. The only
exception is naturally once the data is exported from the Clubhouse, the
Clubhouse loses control, but we know that and consider it.

**Comment by mikeburg** [comment]
One thing to note is if the access date is change on one item thru the Edit Access Documents interface, only that particular item will be updated. None of the other items will be updated for the person.

**Comment by rangerthreepio** [comment]
Yes, however, the Ticketing Team firmly understands that interface, and it
shows you everything side-by-side anyways.

**Comment by plapsley** [comment]
Having "edit BMIDs" change the access date on all SCs and WAPs makes sense to me.  Having Edit Access Docs be able to change the date on one such thing seems like a little bit of a sharp edge but not too bad for the reasons that Threepio mentions.

**Comment by rangerthreepio** [comment]
Yea, and I'm not proposing changing anything about how edit access docs
works.

**Comment by mikeburg** [comment]
What might be better is to relocate the access dates from the access_document table to a new table access_document_dates.  Each row in the table would represent a person with their access date, and  the SO access date.  This way the Clubhouse doesn't have hunt thru multiple records to try and figure out which is the best access date to use OR worry about hunting down all records to update when the date changes. in one given location.

Other benefits to this approach are:
* the access dates could be set or manipulated before any tickets are entered
* the UI would be consistent between the Edit Access Documents and BMID interfaces. You update the access date in one place and don't worry about multiple records.
* the access date record could be retained for historical purposes, and provides a backup in case all items are accidentally deleted.

The downside to this approach is we lose the ability to have different access dates for each SOWAP. (e.g. Hubcap has two SOs Hubcap Jr. and Hubcap Sr. - he couldn't request Jr have one date, and Sr. have another.) But I suspect that situation is never handled in the first place? 

Something to think about for 2020.

**Comment by rangerthreepio** [comment]
Yea and I think we don't want to use that approach for the
following reasons:

   1. Rangers must be able to request SO WAPs for dates other than their
   own (i.e. Hubcap's SOs are arriving on 8/22, but he is coming on 8/19)
   2. We should not change access doc dates for any RADs which have been
   submitted. The date the RAD had on it when it was submitted MUST be
   preserved so that we know whether we need to reorder it, or supercede it
   with a WAP if it was ordered for the wrong date.

But yea, lets talk about this in the fall.

**Comment by mikeburg** [comment]
> 1. Rangers must be able to request SO WAPs for dates other than their
   own (i.e. Hubcap's SOs are arriving on 8/22, but he is coming on 8/19)
Sorry, I wasn't obvious. Clearly there would need to be two columns, the access date for the person, and the access date for the SOs.

**Comment by rangerthreepio** [comment]
Yea, even still, we probably do want to be able to request SO WAPs for
individual dates, and my issue #2 is the bigger of the 2.

**Comment by rangerthreepio** [comment]
Sub issue within this thread (which can be broken out if necessary):

SO WAPs do not inherit the date of unclaimed items, thus when Rangers request SO WAPs, but no RPT or SC, the SO WAPs are undated by default and there is no code which prevents that from remaining in the database until someone notices and fixes it. This happened this year.

**Comment by rangerthreepio** [comment]
@mikeburg - the above comment from 9/24/19 - should it be a separate issue. it's so buried here that I fear it will be ignored (took me 10 minutes to find)

**Comment by mikeburg** [comment]
Closing this out since editing the BMID access date  will update any S.C.s and WAPs associated with the user. This issue can always be reopened later if things are still "treacherous".
