### ISSUE TITLE
Timesheet confirmation: "No more outstanding tasks" when there are two remaining to verify

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#1804]
I loaded https://ranger-clubhouse.burningman.org/client/me/timesheet?year=2023 and saw that I had three timesheet corrections that showed as "The correction request has been approved.  You will need to verify the correction is accurate."

I clicked "Mark entry as correct" on the first entry and a dialog popped up saying

> Congratulations! You have marked the last timesheet entry as correct, and there are no pending correction or missing timesheet entry requests. Please confirm no further confirmations will be submitted, and your entire timesheet is correct by the "Confirm Final Confirmation" button.
>
> In case you have additional corrections to submit, use the "Cancel" button to clear this dialog, and submit the requests.

The first sentence is incorrect; I marked the first as correct, not the last one.

The same thing happened when I confirmed the second of three.

(Bonus usability note: it would be nice if this page showed the note I left when requesting the correction, since it's been a couple weeks, and I don't remember exactly when I started a shift that I neglected to sign in for.  I see that message is shown in the dialog when requesting another correction, but you don't notice that if you're deciding whether to click the Confirm button.)

**Comment by mikeburg** [comment]
Fixed. Closing out.
