### ISSUE TITLE
Counted hours differ in "YYYY Summary" vs. "Work history".

### ISSUE THREAD

**Issue by climent** [burningmantech/ranger-clubhouse-web#1806]
Looking at the amount of hours worked in 2023, there is a discrepancy in the counted numbers on the 2 tabs of the timesheet that summarise the year.

Position | Total Duration
-- | --
Dirt | 22:08
Gerlach Patrol | 8:18
Tech On Call | 24:11
Tech Ops | 38:00

vs

Position | 2023
-- | --
Dirt | 22.15
Gerlach Patrol | 8.31
Tech On Call | 24.19
Tech Ops | 38.00

Is that WAI?

**Comment by mikeburg** [comment]
It's not a discrepancy -- the first table is in hours and minutes. The second table is in hours and partial hours. The reason for the later is geared towards seeing how close a person is to an awards boundary and for the people working with spreadsheets to do awards. 

Closing this out.

**Comment by climent** [comment]
Oh my, can someone explain how i missed the X:XX vs the Y.YY??!?

Thanks for the prompt response and the explanation.
