### ISSUE TITLE
Root resource goes to Classic instead of v2 after login

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-web#19]
Once I'm logged in, if I go to the [root URL](https://ranger-clubhouse-staging.burningman.org/), I get the Classic UI instead of v2.

**Comment by mikeburg** [comment]
I suspect the top level nginx server is routing the root url to the Classic server instead of C2. 

However, Classic should be redirecting back to C2 when the original home page is hit. A fix has been pushed on the secret clubhouse branch to deal with that.

**Comment by wsanchez** [comment]
Yup, fixed.  Note that the top-level Nginx has no idea that Classic is a thing, so that's not it.

But the load balancer in front of everything sends requests to `/api/*` and `/client/*` to the v2 services and everything else to classic.

So… question: I don't think anything outside of `/clubhouse/*` needs to go to Classic, right?  If that's the case, we can route that path to Classic and have the default go to v2 web, which would save a fairly common redirect from `/`.

(This was part of my motivation for putting Classic at that path instead of at `/` when we set it up on AWS; it let's us treat it as a peer of other apps at the LB.)

@mikeburg lemme know if it makes sense to try that out on staging.

**Comment by mikeburg** [comment]
Totally make senses and yes, nothing outside /clubhouse/* should go to Classic. Give it spin on staging.

**Comment by wsanchez** [comment]
OK.  Here's what's going on now:

 1. If host is `rangeroffice.burningman.org`, redirect to `ranger-clubhouse.burningman.org`
 1. If path is `/api/*` and host is `ranger-clubhouse.burningman.org`, ➜ prod API app
 1. If path is `/client/*` and host is `ranger-clubhouse.burningman.org`, ➜ prod web app
 1. If path is `/clubhouse/*` and host is `ranger-clubhouse.burningman.org`, ➜ prod classic
 1. If path is `/` and host is `ranger-clubhouse.burningman.org`, ➜ prod classic
 1. If path is `/api/*` and host is `ranger-clubhouse-staging.burningman.org`, ➜ staging API app
 1. If path is `/client/*` and host is `ranger-clubhouse-staging.burningman.org`, ➜ staging web app
 1. If path is `/clubhouse/*` and host is `ranger-clubhouse-staging.burningman.org`, ➜ staging classic
 1. If path is `/`, redirect to `/client/` (on same host, keep query)
 1. If path is `/api`, redirect to `/api/` (on same host, keep query)
 1. If path is `/client`, redirect to `/client/` (on same host, keep query)
 1. If path is `/clubhouse`, redirect to `/clubhouse/` (on same host, keep query)
 1. Else: 404

1 is for the legacy host name.
2-4 route the production apps.
5 routes `/` for prod.  It can go away when we turn on the v2 apps in prod because #9.
6-8 route the staging apps.
9 redirects `/` to `/client/` on any host.
10-12 are a bit pedantic and are there to redirect the non-collection base URLs to append the trailing '/'.  This shouldn't really happen except for people typing URLs in manually.
13 is catches anything else.

**Comment by wsanchez** [comment]
Before:
```console
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/"
HTTP/2 301 
date: Thu, 07 Mar 2019 20:39:48 GMT
content-type: text/html
content-length: 178
location: ./clubhouse/
server: nginx

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

After:
```console
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:39:54 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse-staging.burningman.org:443/client/

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
```

Note the load balancer is now handling the request directly and going to the v2 web app path.  Also using a full URL because reasons, but that shouldn't matter other than the extra bytes.

**Comment by mikeburg** [comment]
So. many. if. statements! The routing looks good tho, and appears to be working on staging correctly. Thanks.

**Comment by wsanchez** [comment]
Staging looks good for all URLs:

```console
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/api"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:55:06 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse-staging.burningman.org:443/api/

...
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/api/"
HTTP/2 403 
date: Thu, 07 Mar 2019 20:55:09 GMT
content-type: text/html
content-length: 162
server: nginx

...
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/client"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:55:11 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse-staging.burningman.org:443/client/

...
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/client/"
HTTP/2 200 
date: Thu, 07 Mar 2019 20:55:12 GMT
content-type: text/html
content-length: 2661
server: nginx/1.15.9
last-modified: Thu, 07 Mar 2019 20:28:25 GMT
vary: Accept-Encoding
etag: "5c817ee9-a65"
cache-control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
accept-ranges: bytes

...
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/clubhouse"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:55:23 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse-staging.burningman.org:443/clubhouse/

...
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/clubhouse/"
HTTP/2 301 
date: Thu, 07 Mar 2019 20:55:26 GMT
content-type: text/html; charset=UTF-8
server: nginx
x-powered-by: PHP/7.2.1
set-cookie: PHPSESSID=c017a4a324b746f7c78958bfd5526861; path=/
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
location: /client/logout

...
wsanchez$ curl --include "https://ranger-clubhouse-staging.burningman.org/"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:55:32 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse-staging.burningman.org:443/client/

...
```

**Comment by wsanchez** [comment]
And production:

```console
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/api"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:58:25 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse.burningman.org:443/api/

...
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/api/"
HTTP/2 503 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:58:28 GMT
content-type: text/html
content-length: 178

...
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/client"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:58:37 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse.burningman.org:443/client/

...
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/client/"
HTTP/2 503 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:58:40 GMT
content-type: text/html
content-length: 178

...
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/clubhouse"
HTTP/2 301 
server: awselb/2.0
date: Thu, 07 Mar 2019 20:58:50 GMT
content-type: text/html
content-length: 150
location: https://ranger-clubhouse.burningman.org:443/clubhouse/

...
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/clubhouse/"
HTTP/2 200 
date: Thu, 07 Mar 2019 20:58:54 GMT
content-type: text/html; charset=UTF-8
server: nginx
vary: Accept-Encoding
x-powered-by: PHP/7.2.1
set-cookie: PHPSESSID=a73db9f0721822bb1c54debdd8cba687; path=/
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache

...
wsanchez$ curl --include "https://ranger-clubhouse.burningman.org/"
HTTP/2 301 
date: Thu, 07 Mar 2019 20:58:58 GMT
content-type: text/html
content-length: 178
location: ./clubhouse/
server: nginx

...
```

**Comment by flwyd** [comment]
For completeness, I'll note that http://rangerschedule.burningman.com/ and http://rangeroffice.burningman.com/ still exist, and I'll bet some folks have them bookmarked.
They both return `<meta HTTP-EQUIV="REFRESH" content="0; url=https://rangeroffice.burningman.org/">` so they can continue doing that for now.

They look like they're on blaster, though, so eventually we may need to do something with them.

**Comment by mikeburg** [comment]
Who would be responsible for updating the DNS records for rangerschedule & rangeroffice.*.com? BMIT?

**Comment by wsanchez** [comment]
Oh, `.com`.  I never knew about `rangerschedule`.  I'll open a ticket for to track that separately.
