### ISSUE TITLE
Do not print BMID if person NOT (claimed ticket OR signed up for training)

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#1916]
In an effort to waste less, Council wants to avoid printing BMIDs for people deemed unlikely to need a BMID. The prerequisite for printing a BMID is now that the person must have either claimed a ticket or signed up for training.

In addition this modification to the Manage BMIDs interface, Frankenstein recommends adding notifications to the Clubhouse dashboard AND the Person Manage > BMID page  saying the person’s BMID will not be printed if the qualifications are not met.

**Comment by mikeburg** [comment]
Implemented. Please test.

**Comment by techxorcist** [comment]
Tested and worked as expected. Thank you.
