### ISSUE TITLE
Ensure various reports do not unintentionally leak data

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#208]
At least one report -- People By Special Team --  will leak email addresses to a user who does not have the appropriately privileges. 

The Clubhouse should allow most reports be run by anyone who has the Login Management role, yet redact the email address -- or any other personal info --  for users who do not have additional privileges (View PII, View Email, etc.) which allows viewing of such information.

**Comment by plapsley** [comment]
You mean People by Special Team.  People by Role doesn’t show email addresses at all.  (Porcupine’s original bug report was somewhat confusing, but he was really talking about PBST.)

phil

**Comment by mikeburg** [comment]
You're right. The original comment has been updated.

**Comment by mikeburg** [comment]
We appears to be in good shape here. No recent reports (ha) of reports leaking. Closing this out.
