### ISSUE TITLE
2022 TRS address collection requirements

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#211]
Starting in 2019, the TRS requires addresses for all unpaid items (Gift Tickets, WAPs, WAPSOs, Vehicle Passes, etc.). The Clubhouse failed to collect the addresses needed for said items. 

In 2022 (previously 2020 & 2021), the TRS ticketing team should be contacted, and confirm with them if the address will still be required. If that's the case, the Clubhouse will need to be fixed so as to collect the address when the person claims their goodies.

**Comment by techxorcist** [comment]
Ticketing has been asked this question. As of March 25, 2022, the answer is pending.

**Comment by mikeburg** [comment]
For 2022, B.M. ticketing is not requiring the department to collect addresses. (And lo, much rejoicing was had!)) Mailing addresses, if needed, will be asked for when the end-user during check out on the main ticketing website.

Closing out.
