### ISSUE TITLE
Revisit Grant WAP action

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#225]
In past years, the Grant WAP was usually run once per season when dates and deadlines were "relatively" static.

In recent years, the dates and deadlines for issuing WAPs has moved around a bit, and multiple rounds of WAPs are now issued. Clicking the button once per season is no longer an optimal workflow.

Before the Grant WAP feature is ported over from Clubhouse 1, a discussion needs to be had on how to rework the feature to deal with multiple rounds of granting WAP based.

**Comment by wsanchez** [comment]
Dup of #267
