### ISSUE TITLE
Enforced No Canada Addresses in Tickets and Stuff

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#252]
BM Ticketing will not mail to Canadian addresses as of 2019, which means ONLY US addresses are permissible for mailed items (VPs and RPTs). 

I have a note from 2019 that the clubhouse either did not enforce this, or that the language in the clubhouse was not strong enough. 

In one case, a Ranger used the BM Ticketing interface to enter a Canadian address after ordering their items through the clubhouse and reading our text that said "no Canada for you!" so yea. 

More finding out is necessary, perhaps testing a user workflow.

**Comment by mikeburg** [comment]
Did a user actually submit a Canadian address through the Clubhouse ticketing page? It would be pretty damn hard considering the state field only presents US state names. 

There's already language in red bold text saying tickets cannot be shipped to Canada, and only US addresses are allowed. 

Between those two I'm not sure how much more gatekeeping can be done on preventing a user from trying to enter a Canadian address.

As a reminder, here's a screenshot of the Clubhouse ticketing address form looks like:

![image](https://user-images.githubusercontent.com/1523824/65624696-40a66c80-df7f-11e9-9374-b4e422f9c443.png)

**Comment by rangerthreepio** [comment]
No Rangers were able to get an Canadian address into the clubhouse, but one entered one into the here.burningman.org website after interfacing with the clubhouse. I am sending them some EMBER feedback about why their site doesnt actually prevent things like that, and why they yelled at US when one of our volunteers entered a Canadian address into their broken website.

I made a note about this knowing that the clubhouse has big red text, and code that successfully prevents Canadian addresses. I cannot remember why, so let's leave this open for now and I'll try to find out more.

**Comment by wsanchez** [comment]
@rangerthreepio We don't want to track issues in other systems here.  Please follow up with ticketing using stickies to track progress.
