### ISSUE TITLE
Update ticketing email alias references

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#253]
Clubhouse Ticketing currently references donotreply@events2email.com, which is where DGS2 emails come from, whereas emails about Rangering Ticketing come from burningman@events2email.com (don't ask us why, we don't know).

We might defer this change for a few months in case BM Ticketing changes those email aliases again. We have an outstanding EMBER report which gives feedback that using that email alias is resulting in lots of emails going to spam, though changing it annually also results in lots of emails going to spam.

**Comment by rangerthreepio** [comment]
Update: this should be a setting. YF is on that.

**Comment by mikeburg** [comment]
Yup, the Clubhouse uses two setting TicketVendorName to show the name, and TicketVendorEmail for the email address. Either one can be updated at anytime through Admin > Clubhouse. Closing out.
