### ISSUE TITLE
"Force" Enroll Command does not disambiguate which behavior is being overridden

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#254]
Currently the Clubhouse has language preventing multiple training enrollments, as well as language preventing signing up for a full training. Trainers (and others?) can "force" enroll someone. At present, when that happens, it overrides both rules. 

This causes a situation where a Trainer force-adds a Ranger or PNV to a full training (because they know they have an extra seat), but in the process, allows that PNV or Ranger to sign up for a second training. The converse is also true. In several (many?) cases this year, this lead to Trainers/Mentors/VCs violating the multiple enrollment rule accidentally, and/or may have lead to Trainers/Mentors/VCs exceeding the training size cap when trying to force them past the multiple enrollments rule. 

It would be useful to run a query of how many times "force" was used, and by whom, and then decide whether it's working as intended, creating issues, obfuscating problems (as I think it is), and/or needs to be replaced by other code, or just modified to force the user to actually take accountability for using the command.

**Comment by mikeburg** [comment]
The Clubhouse needs to warn and confirm with the user when force adding a person to a training session.

**Comment by rangerthreepio** [comment]
Solution: dialog calls out what is being overridden, multiple enrollment and/or full training. Just to confirm that the force override user understands ALL the consequences.

We'll ask Saturn how TA wants to deal with this.

**Comment by mikeburg** [comment]
The Clubhouse has been changed will alert the user to a potential conflict (multiple training sign up, already started session, etc) and ask to confirm the student sign up.

In addition, the Add Person button has been restricted, per TA's request, to certain individuals on the training cadre - i.e. those with Clubhouse Admin privs. For clarification, this restriction is only for the Training module and does not apply to the ART modules.

Closing this out.
