### ISSUE TITLE
New Unified Flagging View for PNVs

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#255]
Summary: New Unified View for Trainers/Mentors/VCs/Personnel which allows all relevant folks to track flagging of PNVs, add and edit flags, and retain flagging and bonk information from year to year. 

Method Suggested: This could be a modified version of the existing Mentor Cadre view with visibility to Trainers or TA, VCs or VC Cadre.  It could also be a new view which makes a portion of the existing Mentor interface redundant. I have specific ideas prototyped which have been proposed to the Intake Team in fall 2019, and deferred for implentation to 2020. 

Requirements
- The 2019 Flagged Alphas document is largely what we want to reproduce, though it is based on Mentor Cadre-formatted spreadsheets, and is not necessarily the ideal format for all teams to view and/or edit. 
- There will be needs to silo portions of this view from different teams/positions.
- Ideally the view will be a matrix which presents VC flags/notes, Trainer flags/notes, Mentor flags/notes, and personnel flags/notes for the entire current class of PNVs (and possibly auditors). 
- Mentor Cadre, TA, and VC Cadre members will need to see all flags other than Personnel.
- Mentor Cadre, TA, and VC Cadre members will need to be able to edit their own flag/notes fields for each person. 
- It will be helpful to log edits to fields so that we can understand who placed what flags, when.
- A running log of notes would be better than an editable field that a given person can clear.
- Personnel manager (and possibly PIs) may need to see all flags and history. 
- Mentors may desire to hide certain notes from VCs and TA, though Personnel should be able to see all.
- Personnel will likely not want any of their notes visible to anyone else. 
- It is desirable for all teams to be able to see all past flagging notes for anyone in the current year's class, other than those explicitly hidden by Mentor Cadre or Personnel (or not normally viewable based on your position, i.e. Personnel notes might never be viewable by VCs, regardless of age)
- It may be also desirable to view past years classes (say in a Personnel investigation where the PI wants to understood who knew what, when, and what did they say, and where, but the subject of the investigation is an Active Ranger who passed two years ago). 

Background: As of 2019, the Mentor Cadre view was designed to incorporate data from several places, giving the Mentor Cadre an at-a-glance view of VC and Trainer flags. The process was intended to accumulate data from VCs and Trainers to Mentors, but not from year to year, or from Mentors to anyone, or from anyone to Trainers or VCs. This was a flawed approach which keeps most of the intake team in the dark, and fails to preserve information year to year, where many problematic PNVs drop and return. It also fails to surface any of this information to the Personnel manager. 

As of 2018, the Intake Team has been using a unified flagging spreadsheet which surfaces flags to the Mentor Cadre, the VC Cadre, and the Training Academy, and from those groups, the flags can be communicated to the Trainers and Mentors as appropriate. The reasons for this spreadsheet are:

1. VC flags have not been adequately surfaced to the TA or Mentor Cadre since Salesforce was implemented in 2015 (and the automated system for communicating VC flags never worked as intended)
2. There has never been an adequate mechanism for the Mentors to communicate end-of-cycle Mentor flags to future VCs, Trainers, and Mentors (aside from internal Mentor Cadre notes, which did not track handle changes, or PNVs who skipped years between applications)
3. There has never been a transparent information system which allows all groups to comment and see each others' notes, including the Personnel manager's interest in the flags and the flagging process.

**Comment by wsanchez** [comment]
@mikeburg and @plapsley will talk to Threepio about his morning drink intake and go from there.

**Comment by rangerthreepio** [comment]
Next step: 3po and Eucalyptus will use stakeholder process to develop a
requirements doc from the Needs of TA, Mentor Cadre, Personnel, VCs, and RRN

Current concept is a horizontal array interface which lists PNVs (and
auditors?) down the left, and gives TA, VC Cadre, Mentor Cadre, and
Personnel differing amounts of view and edit access to fields for Regional
Flags, VC Flags, Trainer Notes, and Prior Mentor notes. The goal is to silo
the information to the people who need it, but share it automatically with
those who do, and to retain it associated with Clubhouse accounts for
Personnel's use if needed.


   - Regional Flags would be a new field in which the RRN Cadre can add
   notes that have emerged from the community about PNVs
   - VC Flags is currently a hidden field in the clubhouse which is
   imported from Salesforce, but not editable by anyone, or viewable by anyone
   except mentors. we'd just change that.
   - Trainer Notes wouldn't change, just be available in this new view
   (which sorta replaces/augments the current view the Mentors use to see them)
   - Prior Mentor Notes would be a new field in which the Mentor Cadre can
   summarize the Mentor notes in a relatively sterilized, sharable way, for
   future VCs and Lead Trainers to see during future intake cycles.

More after we do out requirements doc

**Comment by mikeburg** [comment]
The first part of the UFV has been deployed: https://github.com/burningmantech/ranger-clubhouse-web/pull/464.

The following items have been implemented:
- The Unified Flagging View under Vol Coors & Person Manage
- The Training manage session page has been restructured to increase note visibility and encourage better trainer notes.

In March, the Salesforce import will be changed to grab the VC comments, and Known PNS/Ranger fields.

In April, all the agreed upon Mentor changes will be tackled.
