### ISSUE TITLE
Auditors and Past PNVs don't receive "Known Rangers," or "Known PNVs" field information

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#256]
Auditors in the clubhouse are set up by the end-user. Past PNVs are already in the clubhouse.
As a result, if they are converted to Prospectives during the intake process, there is no way for the VCs to modify and update their "Known Rangers" and "Known PNVs" fields when they are converted. This has meant that dozens if not hundreds of Prospective Rangers in the last 4 years have been put through Mentoring without the Mentors having any information about their friends in the class, or the department. 

Suggested fix is making those two fields visible to VCs who do the manual conversions when we set up Past PNVs and Auditors as Prospectives.

**Comment by wsanchez** [comment]
Phil can translate from protocol droid.  Workflow issue for VCs.

**Comment by rangerthreepio** [comment]
We should ask Mentors if we need to keep doing this, since they ask at the beginning of the season anyways. 

Are they already checking this information.

**Comment by mikeburg** [comment]
Closing this out since this will be covered by the Unified Flagging View.

https://github.com/burningmantech/ranger-clubhouse-web/issues/255

**Comment by rangerthreepio** [comment]
Be aware - I am asking BM Tech for a new field in SF, which will need to be
imported by CH and populated into Unified Flagging. It was a stretch goal,
and they didn't push back as much as I thought.

**Comment by mikeburg** [comment]
Let's keep the discussion over at #255
