### ISSUE TITLE
Multiple Enrollment in Trainings/Alpha Shifts Confuses Users

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#257]
Worth studying this issue as my review of Scheduling Action Log from April through September of this year revealed that dozens of people ran afoul of this issue, many of them repeatedly. We might test why it's resulting in so much confusion. 

Likely, the original requirement was merely a block to prevent this, when what the end-user really needs is actionable information about how to do it right, not just a surprise barricade which stops and confuses them.

**Comment by wsanchez** [comment]
Need to discuss desired workflow with training academy.

That you can't sign up for multiple trainings is intentional.  Is the problem that no explanation is offered as to why?

**Comment by Nobooty** [comment]
This affects the ART Training as well.
It was most confusing to Rangers who missed their training without dropping it from the clubhouse before the training started. When they tried to sign up for a replacement training then they would be blocked because of the previous past sign-up. It was a surprise if they had only signed up for one training and had not seen the block before.
A simple fix for that would be to ignore trainings in the past when checking.

**Comment by rangerthreepio** [comment]
>
> Is the problem that no explanation is offered as to why?


Yes.


>  A simple fix for that would be to ignore trainings in the past when
> checking.


While that might be a good fix for ART Trainings, it is not a good
all-around solution. I believe VCs are proposing that we add an explanation
so that people who are intentionally signing up for a second training (e.g.
because they missed the first one) can do so, but people who do not have a
good reason to sign up for a second slot are discouraged from doing so.

-Threepio

**Comment by mikeburg** [comment]
> To @Nobooty's point, we're starting to see some ARTs separate from the training in my area as well; Rangers _should_ be able to sign up for a training and an ART offered at a different time.

The Clubhouse does not prevent a person from signing up for a Training and ARTs of different kinds. The blocker will prevent a user from enrolling into multiple sessions of the same type. e.g., Hubcap can sign up for a single Training, a single Green Dot ART, a single Trouble Shooter ART, etc. but the Clubhouse will not allow him to sign up for two or more Trainings, two or more Green Dot ARTs, etc.

The blocker was put into place at the request of the TA -- people were hedging their bets by signing up for multiple trainings and then only choosing one to attend based on which one was the most convenient when the time came. This throws off trying to figure out how many trainers are actually needed for a session, and prevents other people from signing up.

**Comment by mikeburg** [comment]
@threepio correct me if I'm wrong, but the original problem is NOT the student trying to sign up for multiple sessions BUT the fact the trainers were force adding students into full sessions and said students had already been signed up in another  future session. Worse, the future session was full, and the student was not removed from the original session.

For reference here's the language on the student blocker -
"You may only sign up for one Training session. Multiple enrollments are not allowed. If you missed a class and need to sign up for another session, you will need to contact the Training Academy. Contact <hyperlink of TA's email address> for help.

You are allowed to sign up a training session and different ART Training sessions. For example, you may sign up for one Training session, one ART Green Dot session (if qualified), and one ART Sandman session (if qualified).
"
So, it's not how the Clubhouse acts towards the student  but the language & behavior on the warning dialog for the trainers that are force-adding a student to a session. A trainer should be given heads up on what's about to happen, and some help on cleaning up the potential mess. ("Hey Trainer Hubcap, you're about to sign up this student who is already enrolled in another session.. do you want remove them from the other session and sign them up for this new one?")

@Nobooty A discussion needs to be had with the ART cadres regarding if the blocker should allow a student to sign up for a future session if a past session was missed. TA wants students to get in touch to plead their case on why they should be allowed to sign up for a future session when they missed a past one without bothering to remove themselves from the past session. The lack of personal responsibility may indicate problems with a PNV. Yes, life does happen and not everyone can be 100% responsible all the time but its worth trying to figure out if the person simply had bad luck or is inattentive.

**Comment by rangerthreepio** [comment]
>
> correct me if I'm wrong, but the original problem is NOT the student
> trying to sign up for multiple sessions BUT the fact the trainers were
> force adding students into full sessions and said students had already been
> signed up in another future session. Worse, the future session was full,
> and the student was not removed from the original session.


This is a problem we had this year, but it I'm not sure it's the "original
problem" in the context of this Issue. The fact that the code stops people
from signing themselves up twice, but is still resulting in multiple
attempts to do so is what this Issue is about. People either aren't reading
the message, or aren't understanding it, or it's not being delivered as we
expect it to be. Also, making every single instance have to go through the
TA is probably not wise since people can solve this issue themselves if
they are able to remove themselves from a training that hasn't happened
(though that's not always the case).

So, it's not how the Clubhouse acts towards the student but the language &
> behavior on the warning dialog for the trainers that are force-adding a
> student to a session. A trainer should be given heads up on what's about to
> happen, and some help on cleaning up the potential mess. ("Hey Trainer
> Hubcap, you're about to sign up this student who is already enrolled in
> another session.. do you want remove them from the other session and sign
> them up for this new one?")


No, it's both. This issue is about the student-facing piece of this (and
also the Alpha-facing piece of this). There is another issue I believe
about the trainer-facing piece of this.

-Threepio

>
>

**Comment by flwyd** [comment]
To add complication, the Sandman AAR noted that _they_ would like people to be able to sign up for more than one Sandman ARTs in a year to get more experience.

**Comment by rangerthreepio** [comment]
Sounds like the question is to Frankenstein about whether it's worth making
it possible to let different ART trainings be handled differently by this
code.

If so, which Cadres want it to work which ways

If not, Cadres will probably have to deal with the fact that the purpose of
the code is to prevent Rangers from filling up trainings and ARTs in an
effort to keep their options open, and that may outweigh the desire of a
given cadre to have it a different way.

Regardless of the ARTs, Ranger trainings should continue to use the
existing code and also we need the warning message to be revised to be more
clear about why they are getting the message and what to do. Currently
people ignore it and just try again repeatedly.

**Comment by mikeburg** [comment]
Back in December 2019, a new "prevent multiple enrollments" flag was added and was turned on for the Training position. No ART positions have been touched (i.e. flag is unchecked and will allow multiple enrollments to occur).

**Comment by mikeburg** [comment]
The Training and Alpha positions have the 'prevent multiple enrollments' flag checked. Both appear to be working to prevent users to sign up for multiple shifts. Closing this out.
