### ISSUE TITLE
Training Rank appears in Trainer View ONLY for Prospectives, Auditors

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#258]
In the Trainer Report View, only Prospectives and Auditors have a Rank field, which means that after Alphas are converted to Actives, their training rank is no longer visible for the year in which they received a rank. Since the Trainer Report view now has past years, its critical we're able to actually view this information for anyone, in any year they receive a rank. At present, it's only visible until they become a Ranger.

**Comment by wsanchez** [comment]
Display, but read-only

**Comment by mikeburg** [comment]
The training report has been fixed - any ranking given to a person will be shown regardless of status.
