### ISSUE TITLE
Export Access Doc View counts AND exports all displayed rows, whether checked or not

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#259]
Export Access Docs view counts all visible rows, including those with green check marks, and those without any check in the box. As in, it counts all rows, not just all selected rows. 

Furthermore, testing shows that it will export all rows, even if only certain rows are checked. This is extremely bad.

**Comment by rangerthreepio** [comment]
@mikeburg

**Comment by mikeburg** [comment]
Note to self - please test.

**Comment by techxorcist** [comment]
Tested by Citizen and 3PO.
