### ISSUE TITLE
Submitted Ranger Access Docs fail to trigger the BMID Sanity Checker

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#260]
Submitted RADs do not appear in the BMID sanity checker, which is a problem since the sanity check is explicitly designed to be run in the period between the ticketing submission deadline and the event, to catch folks who sign up for shifts prior to their WAP date. 

Conversely, the current sanity checker code displays all Rangers with a submitted WAP as having "no WAP" which is obviously ridiculous.

**Comment by mikeburg** [comment]
Another section needs to be added to flag those individuals who have submitted BMIDs yet have signed up for shifts before their access date.

**Comment by techxorcist** [comment]
3PO and Firecracker: Frankenstein's fix looks like a solid one IF it addresses both of the sub issues listed. FC and I have no additional input other than Frankie's suggestion looks good to us.

**Comment by mikeburg** [comment]
The checker will break out submitted WAPs versus qualified/claimed ones with access dates later than the first shift sign up. Please test!

**Comment by mikeburg** [comment]
No reported problems. Closing out.
