### ISSUE TITLE
Export Access Docs page text is out of date

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#261]
Export Access Docs text refers to 2018 TRS file format rules which are obsolete. Needs to be replaced with accurate 2020+ TRS rules.

**Comment by wsanchez** [comment]
Or let's delete the text.

**Comment by mikeburg** [comment]
The page refers to the 2018 limits of 700 items per export. The new 2019 rule is 2,000 items. The text has been changed to refer to the MAX_BATCH_SIZE variable in the export TRS controller.
