### ISSUE TITLE
Updating Name field on RADs does not actually populate the name field

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#262]
Using the edit access docs interface to update the name on an SO WAP does not actually fill the name out into the name field. 

Furthermore, the Update Name field is available for all RADs, even though it is only tracked for WAPs and SO WAPs, which is confusing to VC ticketing team users as a field which is un-update-able.

**Comment by wsanchez** [comment]
@mikeburg thinks this might have been fixed

**Comment by mikeburg** [comment]
Appears to be fixed. Closing out.
