### ISSUE TITLE
Trainers Report View for a given training counts all Auditors and PNVs as "Alphas" 

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#264]
The Trainer Report view for a training (not the print out, but the editable version) counts all Auditors and PNVs as "Alphas" and appears to miscount as well, example, the first training of 2019 shows "6 Alphas" but shows 3 auditors and 2 alphas signed up. 

Worth pointing out that the counts are all off after Rangers are changed from Alpha to Active, meaning these sheets are useless after the mentors change the statuses, and that could be improved if we kept the report view of status static after the training (showing the status they were at the time they attended). Just a thought. I am opening an issue elsewhere about the general issue of having a years drop down in the Trainers view that displays the training history, but counts currently Active rangers as Returning Rangers/Actives retroactively in past years.

**Comment by wsanchez** [comment]
Marking for Later / low priority.  @rangerthreepio Holler if that's crazy talk.

**Comment by rangerthreepio** [comment]
Should count PNVs and Auditors, where PNV=Prospective, past prospectives, Alphas, and Auditors=auditors

**Comment by mikeburg** [comment]
With the Unified Flagging work,  it's possible to determine what the person's status was at a given point of time. The training pages have been updated to take advantage of the status history and the counts reflect the student status at the time of training. Closing out.
