### ISSUE TITLE
Maintenance Tasks could use more verbose response

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#266]
Currently some maintenance tasks display a list of CHIDs performed on, or no information at all. 

We could use a more verbose response which shows Callsigns the task was performed on, any callsigns the task failed on, a count of total people the task was performed on, etc. Other ideas dependant on which maintenance task we're performing.

**Comment by techxorcist** [comment]
3PO:  Suggest we make at least Set SC Access Dates verbose with errors and handles. If we have time, do then for Grant Ranger WAPs, and Grant Ranger VPs.  More after that. We didn't have specific problems I have noted here, except that this is a "fail silently" problem, so it's hard to know which will help most. SC Access Dates and WAPs are super important and taken for granted by Rangers. VPs less so (people will complain if they don't see what they should have).

**Comment by mikeburg** [comment]
Verbosity added to the maintenance functions. Please test!
