### ISSUE TITLE
Grant WAPs was designed to be used once per cycle, but is not used that way

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#267]
Grant WAPs was designed to be used once per cycle based on eligible Rangers who were likely coming to the event. It was later modified to consider things like shift signups so that we could better cover retired Rangers who we'd otherwise not grant WAPs to. Sadly, this addition causes an issue that if the button is pressed once, we miss inactive or retired Rangers who sign up for shifts after the button is pressed. Since those folks are least likely to be familiar with current ticketing protocols, they are already the most vulnerable population to miss out on a WAP. We should reexamine how this function works, and whether a maintenance button is the best way to accomplish this function. fixing the CH2 bugs with the sanity checker would help this, but it requires a Ranger to check the sanity checker regularly during the ticketing season, which is loathsome.

**Comment by mikeburg** [comment]
An automated report has been created to alert the ticketing team when Rangers may need WAPs granted to them.

**Comment by mikeburg** [comment]
Working as expected. Closing out.
