### ISSUE TITLE
RPTs and VP ordered in Edit Access Docs may have delivery methods chooched

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#269]
RPTS and VPs which are ordered from the Edit Access Docs interface may have their delivery method chooched, without warning to the VC user. I do not have more data about this, but it is related to the Edit Access Docs interface not being transparent about the delivery method, and about those new items possibly inheriting the delivery method of a Ranger who's method was locked in by having other RADs submitted.

**Comment by wsanchez** [comment]
This sounds bads but we donts get it what is saying above.  Please describe to more.

**Comment by rangerthreepio** [comment]
I am extrapolating from old notes (and apparently there was a photo at one point, but I have no way of finding it). 

I believe the bug was that if we order an RPT or a VP (mailable items) from the Edit Access Docs interface _after_ other RAD's have been ordered, the newly ordered items may inherit the delivery method (e.g., Print at Home, Will Call, etc) of the previously ordered RADs. This is especially bad because the Edit Access Docs interface doesn't display the delivery method, so the new incorrect or invalid delivery methods aren't visible to the Ticketing Team before we try to submit the order.

**Comment by techxorcist** [comment]
From 3PO: The partial fix was be adding the ability to edit the delivery method in the Edit RAD dialog (and the Add New RAD dialog, which is basically the same dialog) It looks like this has already been done. FC and I just tested it. As well, the Delivery Method is visible on the front end. One thing we might snag is if the delivery method is different for two items, I don't think Tickets and stuff can show that, but that's probably outside the scope of this bug. Let's stick a fork in this one.
