### ISSUE TITLE
New Feature (minor): Need a Delivery Method interface for Ticketing

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#270]
VCs have no way to edit delivery method in Edit AD interface.  We could use a new function to allow us to edit that method manually in the back end, and have that impact the Tickets and Stuff view to the end user.

**Comment by mikeburg** [comment]
An Edit Delivery method was added back on July 18th. Both you and Phil were emailed about the new feature on the same day. 

 Is the 'Edit Delivery Method' button not appearing?

**Comment by rangerthreepio** [comment]
My list of features is from probably before that time, however, I believe this is an extant request:

The Edit Delivery Method interface only edits the selected method for the users entire suite of items, which is really not the way to handle it. We probably need to replace it with the ability to edit delivery method for each RAD. 

The end user should have the current radio button because policy is that they must choose one method for all items. However, in rare cases where a Ranger needs items set to different delivery methods, or when we're ordering late things for someone who's already ordered things, we need to be able to set individual RAD delivery methods, and view them. Changing the user delivery method after items have been ordered is dangerous because it obscures the original intent of the Ranger to acheive a short term result.

**Comment by mikeburg** [comment]
Closing this out - the plan is have each access document record have its own address information.
