### ISSUE TITLE
Set specific DateTime for Currently On Duty report

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#273]
Submitted by email from Nobooty:

It'd be very useful to be able to set a specific DateTime for the 'Currently On Duty' clubhouse report.

Ideally the user would be able to choose:
- A time, (a single time(date), with maybe +- X minutes)
- A time range, 
- A Shift
This has many uses similar to a 'Timesheet by Position' report, and others.

Priority - Useful during post-event timesheet cleanup

**Comment by Nobooty** [comment]
Also useful during the event when Khaki is trying to close out previous shift IMS entries.

**Comment by wsanchez** [comment]
"Currently On Duty" ➜ "On Duty" with a default of now

**Comment by mikeburg** [comment]
Implemented by https://github.com/burningmantech/ranger-clubhouse-web/pull/328.

**Comment by mikeburg** [comment]
Appears to be working.
