### ISSUE TITLE
Add Ranger Feedback Form link to the Clubhouse home page

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#274]
Submitted by email by Roslyn:

When you get a chance, could you add the link to the Ranger Feedback Form to the Clubhouse home page? 

Our Rangers keep looking for it there and forgetting that it's on the Ranger website, and honestly, since we have most of the other links in the Clubhouse, it makes sense to have that one too. 

Here's the link: https://docs.google.com/forms/d/e/1FAIpQLSfz8AfPZf6u2gsKRFR1iktknGGSCExinLtEut1s3HqpPZkY1Q/viewform

**Comment by wsanchez** [comment]
done
