### ISSUE TITLE
Final checkbox for timesheet confirmation not visible on vertical mobile screen

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#275]
This report came in from Tranquilitea after working with Mantis:
"When completing the steps on her mobile device (in this case a phone) the final check box did NOT appear when the device was held vertical. When held horizontal it appeared."

Mantis added the following details:
"I have a LG V30 - I have been unable to locate in my phone where it tells me what the "version of the operating system" is - Firefox 68.1.1 is the browser I use. 
I have a screenshot of the pages before the confermation screen; however, no screenshots of the page verdical or horizontal. 
At one point during my walk thru with Tranquilitea we were disconnected. During that moment when the phone rang (Tranquilitea was calling me back) I tilted my phone just enough to turn it sideways (changing the screen horizontal) and the box was there. I checked the box and answered the phone, describing the discovery to Tranquilitea. 
I look back at what happened and it could have been that the box was too small and when I saw the screen horizontal it made the box and the font bigger. "

**Comment by mikeburg** [comment]
The checkbox has been replaced with a button. Closing this out.
