### ISSUE TITLE
Training surveys + infrastructure needs to move into the Clubhouse

### ISSUE THREAD

**Issue by plapsley** [burningmantech/ranger-clubhouse-web#276]
There is a whole pile of "training survey" stuff that should move into the Clubhouse.

Every time we teach a training, the Trainers send out a link to a training survey that asks attendees for both quantitative and qualitative feedback about the training.  In addition, there is also a separate training form that trainers use to give feedback to each other.  And then, there is an interface that allows a trainer to see their feedback.  And then there is a management interface that allows the Training Academy to see how trainers stack up and what feedback they have.

Sadly, all of this infrastructure exists outside the Clubhouse, on Phil's privately hosted web server.  It is written in old, crappy (is there any other kind) php.

It uses a .txt file as a database.  This "database" has several years (since maybe 2012) of data that would need to be ported over and moved into the Clubhouse SQL database.

Even more sadly, it needs to move off of this private server: it's not secure, it's not really maintainable, and in general, mission critical code and data should live on Burning Man servers, not on private servers.  (It's a long story as to why it's on the server right now, and Phil can share that with you over a beer).  It should probably move into the Clubhouse.  It would be great to have it as part of the Clubhouse, both for reasons of privacy and authentication, as well as simply ease of use.

This is a fairly big project.  Not a hard project, but there's a bunch of functionality here.

Moving this should be a high priority for 2020.

Phil

**Comment by mikeburg** [comment]
Surveys have been moved off Safety Phil's machine into the Clubhouse.

**Comment by climent** [comment]
Wohow!
