### ISSUE TITLE
Update from Node 10 to Node 12

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-web#277]

**Comment by wsanchez** [comment]
That would mean changing `node:10.15-alpine` to `node:12.10-alpine` in `Dockerfile`.

No need to install `yarn` after this upgrade, since it's in the image.

**Comment by wsanchez** [comment]
Also don't need `npm config set unsafe-perm true` step, since updated `ember-cli` doesn't have that bug.

**Comment by wsanchez** [comment]
Hrm. Node 12 is not [listed as supported](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md) yet…

**Comment by wsanchez** [comment]
Ah.  Node 12 is "Active LTS" starting on 2019-10-22 per the [Node release schedule](https://github.com/nodejs/Release#lts_schedule).  So, let's check in on Ember after then.

**Comment by mikeburg** [comment]
Node 14 is the current LTS version. Closing this out.
