### ISSUE TITLE
Canceling a Timesheet Correction requires canceling two times.

### ISSUE THREAD

**Issue by climent** [burningmantech/ranger-clubhouse-web#29]
The first time you try to cancel the Timesheet Correction, it complains the notes cannot be blank. A second cancel works.

**Comment by mikeburg** [comment]
Huh, looks like there's a bug with Ember's textarea helper, autofocus and not propagating events properly. ch-form has been changed to use a pure html textarea element which fixes the problem.

What's odd about is none of the other forms show this bug. Only the timesheet correction form.

**Comment by climent** [comment]
Works now.

**Comment by mikeburg** [comment]
Thanks Machete for catching that... closing this.
