### ISSUE TITLE
HQ Window Interface - Ask if the person should be marked off site.

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#291]
The Clubhouse tracks if a person is on site or off site, and utilizes the information for a variety of things. (The language report wants to find all on-site Rangers who speak a given language. Which on-site Rangers can the Shift Muster broadcast send a message to? etc.)

Most Rangers will head to HQ Window to pick up their BMID, and/or begin their first shift.  As a result, close to 100% of all Rangers who work a given year will be correctly identified as being on site.

Marking a person off site is problematic. At the end of the 2019 event, only 35% of the 2019 working Rangers were marked as off site. A Ranger may not say they are done for the year, and/or the HQ Window Worker may forget to mark them as such.

An enhancement to the HQ Window Interface can help  this problem by noticing if the Ranger going off duty has no more shifts scheduled and if so, prompt the worker to ask the Ranger if they are done for the year and begin the site checkout procedure (mark as off site, collect an event radio, thank the person for their service, etc.)

**Comment by wsanchez** [comment]
Note IMS uses on-site to restrict access during the event to people actually working the event.

**Comment by mikeburg** [comment]
Implemented. Please test.

**Comment by mikeburg** [comment]
Closing out.
