### ISSUE TITLE
Incorporate personal vehicle information into the Clubhouse

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#306]
From Chameleon:

The request is basically to incorporate yearly personal vehicle stickers and such into the Clubhouse. Similar to the MVR and motorpool and probably in the same location here are some of my thoughts for example only:

PERSONAL VEHICLE AUTHORIZATION
(this data changes each year)

Personal Vehicle Sticker: "Authorized for Pre/Post Sticker" or "Authorized for Staff Sticker:.

Ranger Door Logo: "Authorized for Permanent Door Logo" or "Authorized for Event-Only Door Logo"

Fuel Chit:  Authorized for Event Fuel Chit or "Authorized for Single-Use Fuel Chit:. 

Amber Light: Authorized for "Ranger-Provided:Amber"

And some check boxes somewhere like the  MVR and Motorpool boxes that can be easily checked and unchecked each year by those authorizing the items

Data would be for each and every year so that you could pull up prior year data
PERSONAL VEHICLE INFORMATION
(this data carries through each year - unless/until someone gets/uses a new vehicle, and they should change the information

The following data under personal info:

Vehicle Make
Vehicle Color
Vehicle Year
License Plant State
License Plate Number

And then a report similar to the Vehicle PaperWork Report showing all this info for that particular year.
Maybe someway to print out a single sheet per person with all the authorized items and their vehicle information

**Comment by wsanchez** [comment]
Attached to 2021.  Can move up if other work wraps up.

**Comment by mikeburg** [comment]
Implemented -- closing out.
