### ISSUE TITLE
Option to show full ticketing history in Edit Access Docs

### ISSUE THREAD

**Issue by plapsley** [burningmantech/ranger-clubhouse-web#309]
I was just investigating a ticket situation for a Ranger who hasn’t been on playa since 2014.  They had a credential but it expired.  I realized that there’s no way in the Clubhouse right now to see expired tickets.  I think in the “Edit Access Documents” there should be a button or checkbox that says “show everything” that would allow a VC to see a person’s full ticketing history.

**Comment by wsanchez** [comment]
Putting in Later bucket on the assumption that this is not a common problem.

**Comment by mikeburg** [comment]
Feature added. Closing this out.
