### ISSUE TITLE
Give end-user option to select their RAD

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#330]
In Tickets and Stuff: For a user with 2+ RADs (SC+RPT, 2+ SCs/RPTs), display the items as a list with their source and expiration years, allowing the user to select which item they want to claim. This lowers Ticketing Team workload by moving this function directly into Rangers' hands.

**Comment by mikeburg** [comment]
This feature was added in 2020. Please test.

**Comment by techxorcist** [comment]
Tested in staging and this looks good to me.

**Comment by techxorcist** [comment]
Tested by 3PO.
