### ISSUE TITLE
Improvements to People by Status Change report

### ISSUE THREAD

**Issue by plapsley** [burningmantech/ranger-clubhouse-web#344]
In the People By Status Change report, a handful of enhancements:

* Add a vintage column (are they currently marked as vintage)
* Add a total years Rangered column 

Both of these would be useful to Council when we're trying to figure out who is about to be marked as retired but who we want to mark as vintage before that happens.  Otherwise we have to look up this info by hand.

Finally, a bug: the default report is titled

People By Status Change: Proposed Changes AFTER the Next Event (Heads-Up)

this isn't correct.  That title is true up until an event happens.  I.e., that is true up to about August 25 or so.  But in September, October, November, and December, it's incorrect.  My suggestion is that Jan 1-Sep 15 it should read as it does now, and Sep 15 afterwards it should say "Proposed Status Changes After the Immediately Past Event" (or maybe just "Proposed Status Changes").

**Comment by flwyd** [comment]
It looks like this got done, based on the output in https://ranger-clubhouse.burningman.org/client/admin/people-by-status-change

**Comment by mikeburg** [comment]
Yup, this was completed. Closing out.
