### ISSUE TITLE
Lambase link redirects instead of opening a new tab

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#41]
Lambase does not return the user to the Secret Clubhouse, the link should open a new tab, as it does in CH1.

**Comment by wsanchez** [comment]
I have no idea what this means, yo

**Comment by rangerthreepio** [comment]
The upload a new photo link (to Lambase) redirects to the Lambase website from the secret clubhouse, I believe it should open a new tab instead of taking the user off of the secret clubhouse. When you complete your work in Lambase, it will not return you to the Secret Clubhouse.

**Comment by wsanchez** [comment]
Aha ok

**Comment by mikeburg** [comment]
Fixed and the staging server has been updated. @rangerthreepio Feel free to verify.

**Comment by rangerthreepio** [comment]
working as intended. thank you!
