### ISSUE TITLE
Clarify Clubhouse interpretation of non-Ranger shifts, years as Ranger

### ISSUE THREAD

**Issue by RangerChameleon** [burningmantech/ranger-clubhouse-web#458]
Current Ranger policy allows Non-Rangers to work certain shifts (currently only Logistics shifts) and requries Non-Rangers to have a clubhouse account when doing so. Non-Rangers receive the same resources as Rangers working shifts (meals, showers, tickets), which is why hours worked are tracked.

Currently the Clubhouse does not differentiate between Rangers and Non-Rangers when it comes to years worked as a Ranger.  Therefore Non-Rangers can work several years before becoming a Ranger (if at all) and the Clubhosue will show them as having worked as a Ranger when in fact they did not.

This can be an issue when joining a team that requires a certain number of years before joining the team, as the Clubhouse would indicate X years worked.

Also, a Non-Ranger could work a few years, then try to become a Ranger and be bonked (ouch), yet the system would show they have worked X years as a Ranger.  If they pass then the number of years as a Ranger would not be accurate, which could affect training requirements as a binary.

Also, a Regional may want to know how many years someone has been a Black Rock Ranger and someone could simply look at the years, not realizing their status was "Non-Ranger", and actualy may not have been a BRRanger for some or any of those years.

Clubhouse needs to track the shifts of Non-Rangers, but not count those years as worked as a Ranger.

- Created by Chameleon, who is submitting this ticket in response to a Council Action Item: "Create GitHub ticket to clarify Clubhouse interpretation of non-Ranger shifts, years as Ranger"

**Comment by mikeburg** [comment]
Timesheet entries have a new field 'is_non_ranger" to track Non-Ranger work.  Various reports have been updated to exclude  non-ranger entries where appropriate. On a user's home page, and on the Person Manage landing page, years worked as a Ranger versus a non-ranger (aka Ranger Volunteer) will be split out.

Closing this.
