### ISSUE TITLE
Fix Google Form manual review push to Clubhouse reliability issues

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-web#5]
Replace Google Forms for the manual review with Clubhouse feature because the former is a total hack.

**Comment by wsanchez** [comment]
TA likes the functionality in Google Forms… issue for tech is the reliability of the import mechanism.  We should instead fix that problem.

**Comment by mikeburg** [comment]
The Manual Review was killed in 2020 to be replaced by a Learning Management System in 2021.

"My mother said never to speak bad of the dead, only good. The Manual Review is dead. Good." -- Fictional quote from Bette Davis.
