### ISSUE TITLE
People By Status Change modification to handle 2020 extension

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#525]
Due to the 2020 world crises, the decision has been made to extend Clubhouse status changes by one year.

The People By Status Change report will need to compensate for the 2020 extension. E.g.,  if Hubcap was last active in 2017, he would be marked as inactive post the 2020 event. However, with the ordered extension, he will not be marked inactive until 2021.

**Comment by srabraham** [comment]
Looks like this is done. e.g. @mikeburg even put finishing touches on the UI side here https://github.com/burningmantech/ranger-clubhouse-web/commit/8a2679229c86b27337e938a44b1b87d11e972f14

**Comment by mikeburg** [comment]
@srabraham the proposed changes are under Council review and the Clubhouse was updated so they can peek at the changes. Since you're new here, please check first before closing out an issue you didn't work on. A lot of side conversions happen that are not captured in the issues.

Reopening this.

**Comment by srabraham** [comment]
Gotcha, sorry about that. It looked like this issue was just stale

**Comment by mikeburg** [comment]
Council approved the modifications, the report was run, and statuses were updated. Closing out.
