### ISSUE TITLE
Salesforce Import failures

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#54]
**Staging** Build: 2019-03-12 18:32 Tag: v0.1.0+93516bfd

Create Accounts checked
Update Salesforce checked

-account successfully created
**-Salesforce not updated**
**-no confirmation email sent (Staging server doesn't send emails does it?)**

**Comment by wsanchez** [comment]
This is on staging, so that's correct behavior
