### ISSUE TITLE
Salesforce import uses wrong(?) email field

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#55]
Salesforce import appears to be using the Personal Email field from the Salesforce Contact, rather than the Contact Email field from the Ranger object.

The Contact Email field is populated by the user's choice of their preferred contact email between 4 possible email address fields in their burner profile. Using Personal Email supercedes the user's choice. 

This is work confirming with Nondas/Phil in case there was a reason it was written specifically to use Personal Email instead of Contact email.

**Comment by mikeburg** [comment]
The behavior for the CH2 import page is to use the Contact Email first, and then fall back to the home email.

**Comment by rangerthreepio** [comment]
appears to be working as intended.
