### ISSUE TITLE
Crash when refreshing a deleted profile

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#56]
![7](https://user-images.githubusercontent.com/45806097/54234724-e6572a00-44cc-11e9-99ee-95b1b1e7a394.png)

**Comment by mikeburg** [comment]
How about a little more detail on what you were trying to do?

**Comment by mikeburg** [comment]
NVM... apparently I cannot read the subject..

**Comment by rangerthreepio** [comment]
Deleted a test account leaves you on the url of the test account, and in
CH1, search results remain at the left side of the screen. Any of the
following will lead to a crash:


   - Clicking on the Handle at the top of the profile in CH2 (and thereby
   reloading the removed page)
   - Clicking on the handle in the search results in the sidebar of CH1
   (and thereby reloading...)
   - Hitting Refresh (and thereby... you get the idea).

Suggest that it dumps you back to the home page after you manually remove a
profile.

**Comment by mikeburg** [comment]
A fix has been pushed to staging & production.

**Comment by dreness** [comment]
> A fix has been pushed to staging & production.

![citation needed](https://upload.wikimedia.org/wikipedia/commons/3/31/Webcomic_xkcd_-_Wikipedian_protester.png)


(just a little joke)

**Comment by mikeburg** [comment]
The problem is having users. Get rid of the users, and we won't have bugs. Problem solved!

**Comment by rangerthreepio** [comment]
working
