### ISSUE TITLE
Do not cache index.html 

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#6]
When a user hits Clubhouse 2.0 we want to ensure the latest client version is loaded and the old version is not cached in the browser.

To accomplish this, the web server should add a no cache header to the response when serving index.html.

An example nginx configuration would look like this:

```
    location /client {
    	alias /web/clubhouse2/client;
    	index index.html;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        try_files $uri $uri/ /index.html;
    }
```

**Comment by wsanchez** [comment]
`max-age=0` is already coming back:

```console
wsanchez$ curl --include 'https://ranger-clubhouse-staging.burningman.org/client/'
HTTP/2 200 
date: Sat, 02 Mar 2019 18:43:14 GMT
content-type: text/html
content-length: 2637
server: nginx/1.15.9
last-modified: Sat, 02 Mar 2019 03:23:12 GMT
vary: Accept-Encoding
etag: "5c79f720-a4d"
cache-control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
accept-ranges: bytes

<!DOCTYPE html>
...
```

**Comment by wsanchez** [comment]
I'm not sure that's ideal, though.  No caching at all seems inefficient, even if it's a relatively small resource.  I'd suggest a 10-minute cache timeout at a minimum.

**Comment by mikeburg** [comment]
In a traditional static page website, yes no caching would not be ideal or desired. With a SPA the index.html file is only loaded when the user first hits the website. The app takes and page navigation is done within the app  without hitting index.html or any other file for the session.

You can pop open the developer tools and see the network traffic going across. The first few requests will be for index.html & associated resources, after that the traffic will be all API requests.

**Comment by mikeburg** [comment]
Closing this -- index.html is not cached, and the assets with unique finger-printed filename have a 10 day cache period.
