### ISSUE TITLE
Salesforce import blocked without Emergency_Contact_Name_c

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#69]
Salesforce records without emergency contact field show: 

"Missing required field Emergency_Contact_Name__c"

and Import Status: "invalid"

Applicants are not asked for Emergency Contact info in their burner profile, so this needs to accept blank fields (right?!), HOWEVER, this may not have always been the case, and we don't want blank Emergency Contact fields in the clubhouse.

**Comment by mikeburg** [comment]
Clubhouse 1 does require the Emergency Contact Name (EMC) field to be filled in. What should CH2 do? Continue with the old behavior requiring a EMC or allow the record to be imported if the field is blank?

![image](https://user-images.githubusercontent.com/1523824/54623057-02584f80-4a28-11e9-8f03-f14e8a08ab40.png)

**Comment by rangerthreepio** [comment]
This is interesting because as far as I know, CH1 had no trouble getting
emergency contact info until this Spring, when our VCs creating test
accounts were not required to enter emergency contact information in their
burner profiles prior to submission. So, this may be something org tech
changed that now affects us. @Phil Lapsley <safetyphil@burningman.org> would
be the first person I'd and I'd go to org tech second.

**Comment by rangerthreepio** [comment]
Yeah, nothing changed on our end, so I assume this is something that changed on the Org’s side and they’re no longer requiring emergency contact info?

Phil

**Comment by rangerthreepio** [comment]
...opening a ticket...

**Comment by rangerthreepio** [comment]
FWIW: It's too late for Org Tech to help us with this because... we already
have 200+ applications this year, and new 2019 applicants have already been
able to submit a Ranger Subquestionnaire without emergency contact fields
filled in their burner profile, so we'll need to solve this issue for the
applicants in hand even if BM Tech also does something about it for
everyone else.

**Comment by rangerthreepio** [comment]
Update from Deputy at BM Tech:

> Threepio,
> 
> There was a small committee of tech and volunteerism folks who convened last spring and came up with questions and content to be removed from the VolQ (either because it was redundant, or unused, or would be better collected at a different time/juncture). Clearly there were some gaps in the communication, if your team wasn't consulted. 
> 
> Normally we are not this reactive to inquiries about VolQ content, but we realize this data must be important to your team, and for you to collect it yourselves will be a significant burden. 
> 
> So, I am going to take the VolQ down this morning and reinstate those questions. It should be quick.
> 
> It would be awesome if you could help me test afterwards - please let me know if you are available in the next hour or so? We just want to be sure the data is going into Salesforce once the questions are reinstated. I'll submit some Ranger apps myself.

I'm not sure we actually want them to reinstate this for the entire org just to help us with the next 200+ applicants when we already have to deal with up to 200 applicants without emergency contact info. Ideas?

**Comment by rangerthreepio** [comment]
It's worth mentioning that VC instructions already ask all applicants to log in and update their emergency contact information as STEP 1 of our clubhouse invite email. 

As I see it options are:
1 - eliminate the requirement in the clubhouse and hammer on uploaded PNVs to actually do that via NVA; harass the stragglers and threaten them with sticks
2 - have deputy reenable the questions as mandatory in the VolQ and then email all the waiting applicants to go back and re-enter that info in their burner profile
3 - have deputy reenable the questions as mandatory and harass any applicants we already have over email AFTER they are uploaded (combination of 1 and 2)
4 - ?

**Comment by mikeburg** [comment]
4. To add to the already endless requirements for shift sign up in the Clubhouse (photo on file, bpguid entered, passed manual review, blah, blah, blah) - require the the user to have entered their Emergency Contact info.

5. Have the Mentors nag the Alpha when showing up at the hat rack. (I'm sure the Mentors would loovvveee this idea.)

**Comment by rangerthreepio** [comment]
@mikeburg I believe this is fixed, I just tested, but wanted to confirm you're clear of this incident?

**Comment by mikeburg** [comment]
@rangerthreepio everything looks good on my end. I'd like to leave this issue open until after the first batch of PNVs is successfully imported.

**Comment by mikeburg** [comment]
Several PNV batches have been done without tripping up on this. Closing out.
