### ISSUE TITLE
Alpha shifts are now 0.5/hour starting in 2021

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-web#704]
Alpha shifts are now 0.5/hour starting in 2021

**Comment by techxorcist** [comment]
@wsanchez, to clarify, does this mean 10-hour Alpha shifts will be worth 5 credits in 2022, up from 2.5 credits in 2019?

**Comment by wsanchez** [comment]
@citizen: Your math appears correct to me.

**Comment by mikeburg** [comment]
Verified the Scheduling Gnome (err Dwarf) have gnomed the Alpha shift credits to 0.5 per hour. Gnome-ing out this gnome-y issue.
