### ISSUE TITLE
Salesforce Import "expand all" has no corresponding "hide all"

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#71]
once expanded, you are stuck with them.
![9](https://user-images.githubusercontent.com/45806097/54581663-e4a8cd00-49ca-11e9-8dfc-18c39b6fcbeb.png)

**Comment by rangerthreepio** [comment]
appears fixed?

**Comment by mikeburg** [comment]
Okay, closing it out.
