### ISSUE TITLE
Salesforce Import shows previously imported records on next attempt

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#72]
Salesforce import, once completed, if re-run, shows records already imported as "not ready" with hand symbol

I believe it should simply not display them, and also not act on them. Question: what are the criteria for showing them currently?

![8](https://user-images.githubusercontent.com/45806097/54581699-06a24f80-49cb-11e9-8617-9d4616bc7254.png)

**Comment by mikeburg** [comment]
In the screenshot, the SF writebacks  are disabled - meaning the Clubhouse will NOT update the status in Salesforce.

I'll update the page to include a better explanation on what the writeback does.

**Comment by rangerthreepio** [comment]
The screenshot was taken *after *a successful upload with writebacks
though...

**Comment by mikeburg** [comment]
Why, yes, the screen has Enabled and not disabled - BLARGH.. apparently I can't read screenshots now. Please commit me to nearest assisted living facility.

**Comment by rangerthreepio** [comment]
The Black Hole is for Gate Staff only.

**Comment by mikeburg** [comment]
Question - should there be a 'enable write back' option on the actual page, and not rely on the SFEnableWritebacks system setting?

**Comment by rangerthreepio** [comment]
I think I missed this: Update Salesforce (caution) IS SFEnableWritebacks...
right? or it's not and it does nothing?

-Threepio

**Comment by mikeburg** [comment]
SFEnableWritebacks is a bit confusing IMNSO, it kinda feels like a debugging leftover. The flag allows or denies  ALL updates to the SF record.

'Update Salesforce' will update the SF record when the account was successfully created. HOWEVER, that *only* happens when SFEnableWritebacks is true.

**Comment by rangerthreepio** [comment]
So its a second, hidden key which needs to be turned behind the scenes
before this other visible key is turned by the importer.

**Comment by mikeburg** [comment]
Bingo! You have uncovered the Clubhouse shadow government.

**Comment by rangerthreepio** [comment]
So... is the clubhouse importer showing those records because they are test
accounts (even after successful import and a page refresh)?

Obviously we don't want it to persistently show all records including those
which have already been uploaded.

**Comment by mikeburg** [comment]
The current behavior is to show all records regardless of status and if the record is real or not.

So the page should only show those records which are import candidates?

**Comment by rangerthreepio** [comment]
@Phil Lapsley <safetyphil@burningman.org> can comment on this better. I'm
guessing we want it to show all test accounts regardless of status, but
when we do real accounts, it won't display those which are already uploaded
(except immediately after the upload when it displays import successful or
not).

**Comment by mikeburg** [comment]
Issue believed to be resolved but need to keep an eye on it for 2020.

**Comment by mikeburg** [comment]
Appears to be fixed. Closing out.
