### ISSUE TITLE
Salesforce import does not show correct VC status after successful

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#74]
After Salesforce import with Create Clubhouse Accounts and Update Salesforce checked, the page refreshes and Import Status shows "succeeded" while VC Status for successful imports shows "Released to Upload" which is incorrect since they have been updated by the clubhouse to "Clubhouse Record Created"

![10](https://user-images.githubusercontent.com/45806097/54624528-c70b5000-4a2a-11e9-8634-ad3426549133.png)

**Comment by mikeburg** [comment]
The status should report as "imported" now when the VC status is "Clubhouse Record Created".

**Comment by rangerthreepio** [comment]
So to clarify, nothing has changed vis a vis this bug: when you mark records for clubhouse creation and hit "submit" it successfully uploads, marks import status as "successful" and correctly changes their VC status to "Clubhouse Record Created" but still shows their old VC Status in the display, even though it just changed that value:
VC Status = "Released to Upload"
Import Status = "Succeeded" 

If you hit submit a second time (without anything checked) it will reload their correct VC statuses.

**Comment by mikeburg** [comment]
Okay, I restructured the page to group the accounts by status (succeeded, import, invalid, duplicate {email,bpguid,callsign}) with a more detailed label.

Give it a spin.

**Comment by rangerthreepio** [comment]
fixed and closed and thank you!
