### ISSUE TITLE
Clubhouse Welcome Message received somewhat "encrypted"

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#75]
Clubhouse welcome email received in our inboxes in a single code string (not HTML). When we reply/forward, Gmail correctly interprets it into the HTML email format IN BOTH the sent message, and the previously received message. Bugged messages in the same thread in gmail which are not replied to/forwarded/etc remain bugged. 

This issue present both on Miss Piggy's Ubuntu machine with Chrome Version 72.0.3626.96 (Official Build) (64-bit) and my Win10 machine with Chrome Version 73.0.3683.75 (Official Build) (64-bit)

Image from MP's Chrome 72 here:
![12](https://user-images.githubusercontent.com/45806097/54626281-1dc65900-4a2e-11e9-91e1-32b23f608e74.png)

**Comment by rangerthreepio** [comment]
Also an issue in gmail app on Android.

![13](https://user-images.githubusercontent.com/45806097/54627081-d640cc80-4a2f-11e9-89fe-69a6febaadbc.jpg)

**Comment by mikeburg** [comment]
Okay, my theory  is the inline image tag is to blame. Commit incoming to yank it out.

**Comment by mikeburg** [comment]
The inline image has been killed. Try it again.

**Comment by rangerthreepio** [comment]
Appears to be working in Chrome and Android. Not sure if we want to test it further on more platforms.

**Comment by mikeburg** [comment]
Feedback from other folks says this working. Closing it out.
