### ISSUE TITLE
Warn user about missing BPGUID and prevent signups.

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-web#8]
From Safety Phil -

>The Borg uses a thing called a “Burner Profile Globally Unique Identifier”, or BPGUID, to identify people across departments.  In particular, this is now used for thank-you cards, as the thing that links Ranger Hubcap to their Burner Profile.  All new Ranger accounts automatically have a BPGUID assigned to them. Volunteers in all departments are supposed to have BPGUIDs.

>Every year Nondas in Org IT and I have to spend a bunch of time tracking down veteran Rangers who don’t have BPGUIDs, and manually nag them to create or remember their Burner Profile account and tell us what their email address is on Burner Profiles, and then manually fetch their BPGUID and add it to the Clubhouse.  Last year we had to do this for 40 or so people.  It’s a pain in the butt.

> I propose adding a feature to the Clubhouse so that, if you log in to the Clubhouse but you don’t have a BPGUID on file, your account is disabled (“big yellow box”), with instructions telling you how to get one. Until you do, you will be unable to sign up for shifts.  Getting a BPGUID just means you either find or create a Burner Profile, and then enter your email address and Ranger handle into a Google Form.  It takes like 3 minutes.

**Comment by hariboukis** [comment]
Phil, all,

 

Will blocking a Ranger from logging in to the Clubhouse ever lead to a situation where the Ranger shows up on playa, at HQ Window, asking to be marked “on playa” without a BPGUID?  If so, let’s work out a procedure where this can NEVER happen.

 

Thanks

Socrates

**Comment by mikeburg** [comment]
@hariboukis 

The Clubhouse will not prevent them from logging in if there's no BPGUID on file. The site will only prevent the person from signing up for shifts. 

Phil may correct me on this - I would say HQ should be allowed to declare the person on site and allow them to sign in for a shift while having a nag screen the person should go get their BPGUID straightened out.

**Comment by wsanchez** [comment]
My understanding of the decision here was they cannot sign in for a shift, and I don't think it serves the purpose for HQ to override this.

But let's add a bigger pre-playa stick so that HQ is less likely to run into conflicts here.  If no BPGUID, you should not be able to claim a WAP, Ticket, or Credential.  That should catch a lot of people ahead of time.  There may be other such opportunities pre-event.

**Comment by mikeburg** [comment]
Clubhouse 2 will prevent folks from both signing up for a shift and prevent them from claiming tickets. 

Currently there are 14 active and 61 inactive accounts with no BPGUID on file.

**Comment by mikeburg** [comment]
Appears to be working - folks have been bugging the VCs to link their Clubhouse account to a BPGUID. Closing this out.
