### ISSUE TITLE
Alpha Shifts not showing up

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-web#81]
From Chameleon:

> Not sure whether this is a bug or intentional, but it appears CH2 does not track Alpha shifts like Classic CH:
> 
> 1) if an Alpha passes but does not work any Ranger shifts that same year after passing, their Alpha shift does not show up in the Clubhouse (in Schedule or Timesheet)
> 
> For example, the following Rangers passed, but did not work a Ranger shift the same year they passed and therefore no Alpha shift is showing up:
> Pantsless (passed in 2016 and has never worked a Ranger shift)  
> Domo Chan (passed in 2017 and did not work a Ranger shift that year, but did work a burn perimeter in 2018)
> 
> 2) If an Alpha is Bonked, their Alpha shift does not show up in the Clubhouse (in Schedule or timesheet)
> 
> For example, the following Past Prospectives were bonked in 2018 and their Alpha shifts are not showing up (in Schedule or Timesheet)
> ParrisS18B  (Past Prospective)
> McCoyG18B (Past Prospective)
> The following was Bonked 3 times, but none of those Alpha shifts are showing up - finally passed in 2014  
> Paintbrush
> 
> 3) Alpha shifts for passed Alphas that work a Ranger shift that same year show up in the Timesheet, but their Alpha shift does not show up in the Schedule for that year like other Ranger shifts. This appears to apply for all Rangers.
> 
> Perhaps this is intentional since Alpha shifts are not Ranger shifts, but it means the clubhouse is loosing the history of the Alpha shifts for anyone looking up the schedule record of a Ranger.
> 
> The Mentors are showing up for these Alpha shifts under 'Mentors', so perhaps this is where the history is intended to be reflected for Alpha shifts?
> 
> Not sure whether the above observations are intentional or not. And perhaps it is fine not to show Alpha shifts for Bonks or for Alphas that do not work a Ranger shift that year after passing.  
>

**Comment by mikeburg** [comment]
Fixed by #82

**Comment by mikeburg** [comment]
Appears to be working. Closing out.
