### ISSUE TITLE
Global Schedule Report

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#921]
This report would allow people with the Login Management role to view a report of all scheduled shifts, filtered by year. The purpose is to provide an easy way for a person to review schedules that have been set up before the shifts are activated and/or when the person is not assigned to the Position the shifts are for.

**Comment by flwyd** [comment]
I think the schedule page used to have a button that let you see non-active shifts, which was implemented as an easy way for folks to check the planned schedule for their own teams.  (It didn't show positions you aren't a member of, though.)  I'm not sure why that option isn't there anymore.

One easy way to do this would be to grant read-only access to https://ranger-clubhouse.burningman.org/client/admin/slots  
If we implement it as a report we might be able to present the data in a more calendar-like way, though.

**Comment by mikeburg** [comment]
A global report already exists  - Reports > Schedule > Schedule By Position.  The only thing missing is the ability to show inactive reports and that has been covered by this shiny new pull request: https://github.com/burningmantech/ranger-clubhouse-web/pull/922

Closing this out.
