### ISSUE TITLE
Bulk lookup throws 414 error

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#931]
Bulk lookup of 400+ names throws this error:

> A server error was encountered:
> Error: Ember AJAX Request GET /api/person/bulk-lookup returned a 414 Payload (text/html) "\r\n\r\n\r\n
> 414 Request-URI Too Large
> \r\n
> nginx
> \r\n\r\n\r\n"

Lookups of 350 and fewer do not.

**Comment by rangerthreepio** [comment]
![bug](https://user-images.githubusercontent.com/45806097/127533815-bfe44e82-e768-4577-9ceb-f7ce3f861e8f.png)

**Comment by mikeburg** [comment]
Fixed by https://github.com/burningmantech/ranger-clubhouse-web/pull/932

Closing out.
